In [2]:
import numpy as np

# 1. Creating Numpy array

In [7]:
# create a simple array
np.array([1, 2, 3])

array([1, 2, 3])

In [8]:
# create an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [9]:
# create an array of ones
np.ones(3)

array([1., 1., 1.])

In [22]:
# numpy array default type is np.float64
# to specify a data type use 'dtype' keyword
np.ones(3, dtype=np.int64)

array([1, 1, 1])

In [10]:
# create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [18]:
# create an array contains a range of evenly spaced intervals
# (start, end, step size)
np.arange(2, 12, 3)

array([ 2,  5,  8, 11])

In [12]:
# create an array with values that are spaced linearly
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 2. Adding, removing, and sorting elements

In [28]:
# sort array elements in ascending order
arr = np.array([5, 2, 0, 9])
np.sort(arr)

array([0, 2, 5, 9])

In [30]:
# np.sort() does not allow sorting in descending order
# to sort array elements in descending order use list slicling
arr = np.array([5, 2, 0, 9])
arr = np.sort(arr)
arr[::-1]

array([9, 5, 2, 0])

In [34]:
# concatenate two arraies or more
a = np.array([1, 2])
b = np.array([3, 4])

np.concatenate((a, b))

array([1, 2, 3, 4])

In [40]:
# concatenate 2D arraies along axis 0 (i.e. concat rows)
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
# concatenate 2D arraies along axis 1 (i.e. concat columns)
x = np.array([[1, 2], [3, 4]])
y = np.array([[5], [6]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [44]:
# delete elements in 0 index along axis 0
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(arr, 0, 0)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# delete elements in 0 index along axis 1
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(arr, 0, 1)

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [58]:
# delete elements in index 1,3,5 
np.delete(arr, [1,3,5], None)

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])

# 3. shape and size of np.array

In [5]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7]],

                [[0, 1, 2, 3],
                 [4, 5, 6, 7]],

                [[0 ,1 ,2, 3],
                 [4, 5, 6, 7]]])

# to find the dimension of np.array
print(arr.ndim)

# to find the size or how many elements are in the np.array
print(arr.size)

# to find the shape of the array
print(arr.shape)

3
24
(3, 2, 4)


In [10]:
# reshape np array
arr.reshape(4,6)

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 0, 1, 2, 3],
       [4, 5, 6, 7, 0, 1],
       [2, 3, 4, 5, 6, 7]])